### PR TITLE
Enhance Nextjs with Layouts and Markdown

### PR DESCRIPTION
**Pull request by geofmureithi**
**Referenced issue**
#43 

**Summary of changes**

- [x] Start using Next.js layout and Bootstrap components.
- [x] Add ability to render markdown page.
- [x]  Responsive wizard

**Reviewer recommendations**
Vercel allows comments on the Preview link, check it out and leave some comments

### CODE REVIEW

**Review by eloylp — APPROVED** [review]
Things that i checked:

```bash
$ npm install
$ npm run build
$ npm start
```
Then browsed the UI, changed a markdown file (check changes), check responsiveness of the web page. All ok :+1: 
```

**Comment by mariopil** [comment]
The wizard UI doesn't look too good - `Play` button and inputs are cut out:
image
Also some of the contract links point to nowhere (e.g. the voting one)

**Comment by geofmureithi** [comment]
> The wizard UI doesn't look too good - Play button and inputs are cut out.

Hmm interesting, which browser are you using?

**Comment by geofmureithi** [comment]
Interestingly on linux it looks wierd but on mac its looking good

**Comment by mariopil** [comment]
I've checked 2 browsers - on Safari it's fine, problem is on Opera

**Comment by geofmureithi** [comment]
Do you think it is Bootstrap related?

**Comment by mariopil** [comment]
I still have the same issue under Opera. What is odd is that when I open the element inspector everything is displayed correctly:
image

**Comment by mariopil** [comment]
I've played a bit and when I've changed the offset from 4 to 5 on the wizard page for the editor it stopped covering the toolbox:
```
<div className="col-md-8 offset-md-5">
          <Editor
            contractTrait={contractTrait}
            contractName={contractName}
            author={author}
            license={license}
            codeGen={codeGen}
          />
```

**Comment by mariopil** [comment]
Looks perfect now :)

**Review by mariopil — APPROVED** [review]

**Pull request merged**
