### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by eloylp**
This adds the following issue and PR templates for the repository:

**Issue templates**

* `Bug report`
* `feature request` - Mostly for external contributors.
* `New contract` -  Where external contributors can request a new contract to be added.
* `New project feature` - This is mainly for internal contributors. Normally this issues come from pre-planned milestones.
*  `research`  - Investigation issues in which we log our findings, in order to maximize context sharing.
* `security` - Redirects contributors who discover any security bug to a safe email address for notification purposes.

**PR template**

A minimum PR template that promotes instructions for reviewer and also linking to related issues.

### CODE REVIEW

**Comment by eloylp** [comment]
Adding draft PR  for review, hope this is not too overwhelming. I tried to kept templates complexity at a minimum. Let me know your thoughts.

**Comment by mariopil** [comment]
What's the difference between `feature request` and `new project feature`? Is the first one related to contracts only? I would change it's name to distinguish it more from new project features. In the presented form people could get confused which type they should choose.

**Comment by eloylp** [comment]
> What's the difference between `feature request` and `new project feature`? Is the first one related to contracts only? I would change it's name to distinguish it more from new project features. In the presented form people could get confused which type they should choose.

Yeah, similar thoughts here. My intention was to provide:

`feature request` - This is something the project doesnt have on its roadmap, but that due to a non covered use case would be great. So external contributors can say "It would be nice to have ..."

`new project feature` -  This is a bit more free, thought for when we need to add pre-planned issues from milestones. Its not a feature request, its something the project maintainers wants to head towards.

`New contract` - This is specifically for adding new contracts , as it has high probabilities of being one of our main incoming contributions, so just trying to preapre the terrain for it, and condense all the knowledge in that template. I considered a dedicated template for this would play well.

Said that, maybe its good to remove the `new project feature` issue template, as it looks like confusing and its breaking orthogonality with the rest of templates. Internal contributors can adapt the `feature request`  one to be more ad-hoc for milestones, as we were doing till now.

Another aspect to consider is that this are templates. THey should not be taken as a silver bullet, but as a guidance. Personally i would not matter one format or the another while the needed information to process the issue is present.

The idea is to help with the templates to the distracted mind :D  . Let me know your thoughts. Would it be better removing `new project feature` ?

**Comment by mariopil** [comment]
Yeah, I would remove it :)

**Review by geofmureithi — APPROVED** [review]

**Review by mariopil — APPROVED** [review]

**Comment by eloylp** [comment]
Ok thanks guys, removed the `new project feature` template. Merging ...

**Pull request merged**
