### PR TITLE
Feat/downloadable contracts

### PR DESCRIPTION
**Pull request by geofmureithi**
This PR allows us to download contracts that have been compiled in CI.

This is blocked by 
#29 and #22

### CODE REVIEW

**Review by eloylp — APPROVED** [review]
Approved , just need to fix conflicts issues.

**Comment by geofmureithi** [comment]
@mariopil We can combine this PR with [Github Artifacts API](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28) to add back the download feature. I think that would be neat!

**Review by eloylp — APPROVED** [review]
Approved. Is there something else blocking this @geofmureithi ?

**Comment by geofmureithi** [comment]
Not really, just 2 approvals.

**Review by mariopil — APPROVED** [review]

**Pull request merged**
